# - name: "copy files"
#   template:
#     src: "files/artifact.tar.gz"
#     dest: "~/"

# - name: "unzip files"
#   shell: |
#     tar -xzvf artifact.tar.gz

- name: Extract zipped file
  unarchive:
    src: artifact.tar.gz
    dest: ~/
    remote_src: yes
- name: "start app"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start

