- name: "copy files"
  template:
    src: "files/back-end"
    dest: "~/"

- name: "unzip files"
  shell: |
    tar -xzvf artifact.tar.gz

- name: "start app"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start

