# - name: "copy files"
#   template:
#     src: "files/back-end"
#     dest: "~/"

# - name: "unzip files"
#   shell: |
#     tar -xzvf artifact.tar.gz

# - name: extract artifact
#   become: yes
#   unarchive:
#     src: files/artifact.tar.gz
#     dest: .

- name: "start app"
  shell: |
    sudo npm install
    sudo pm2 stop all
    sudo pm2 start npm --name "udapeople-backend" -- run start
    # pm2 start npm -- start

  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_ENTITIES: ./src/modules/**/*.entity.ts
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_HOST: database-1.csub2uflo81x.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: 12345678
    TYPEORM_DATABASE: my1stdb

